# Generated by Django 4.1.5 on 2023-02-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_remove_snippet_lang_alter_comment_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=8)),
                ('full_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='snippet',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MainApp.language'),
        ),
    ]
